language: node_js
node_js:
    - "10"
install:
    - npm install
script:
    - npm run test
sudo: false
dist: trusty

before_deploy:
  - zip -r latest *
  - mkdir dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
branches:
  only:
  - main
deploy:
  provider: s3
  access_key_id: AKIAYB6YCLYJMOTOJXHX
  secret_access_key:
    secure: l7FZ5yCMk5N2wUkLFY6ew95F0BZeI5UspIfTGRifYrxSp+zcWwwMHz5PwRgrY+QycEvPcqbjoA8riG+Sg8UOTJtWiSlXBR0EZBwYCSMFvnfxCJYBQBlDGlWko2G+yc8EGcoOcR6efHBqbSSlxwcQRcJTq3vTaHefwyOMQdBDEiIYv3wqGXRiM1B9gqgH9eQ0/niYg+TA1Wagjo4qvs5Lwcx69F83jZqzSda1x1e9he3qe8szJ3sdC/leEoz25n8zBrk8Ccjc8T/GkfTFoUlYtv32XwgGXdaL2kAEMa1pzJ3/e0qkilmhlKhHxVX1cXePXxkCVZIvEgo2Arv5QVW9tmCkKVskbRVfRceh+hE5wNEEbIEjVX4z4K3kdtroTUxl5BLhrnLdSPzAfKDqAAgBqSx7RmGBf4t2xF367oPKikkMalcoU4PTnjXoLmJMzWhLRWUxQnENiTEGUirdnEagF3NhhtxQwlG/WcE5fm5yl0xmiV2HYceWtbF+nDZc6lTVb5EMrb46JmZl6Z/a2d05yZMhwZIrnlDp4tHWMDnM46+buTV1eyA5Dm+l3kJlhLV/zMoprXHdkRQs3NWraPhRRrb4dPrzS6CFdb8ozlSV45eMAcCl8XJ9bdKnqFFBvlNeGiCa0JkgKMXzdgb2ZbpUmGSqy47xo7j+biDQagQgd7k=
  bucket: travis-deploy-bucket
  local-dir: dpl_cd_upload
  acl: private
  on:
    repo: Lauviah0622/backend-deploy-test
    branch: main
  skip_cleanup: 'true'
  region: ap-northeast-1
