  deploy:
    provider: s3
    access_key_id: AKIAIA2J7HXUI52NHMHA
    secret_access_key:
      secure: JPDcEKISOrS4YK31WC...太長了(省略)
    bucket: bright-travis-deploy
    local-dir: dist
    acl: private
    skip_cleanup: true
    on:
      repo: Lauviah0622/backend-deploy-test