language: node_js
node_js:
    - "10"
install:
    - npm install
script:
    - npm run test
before_deploy:
  - zip -r latest *
  - mkdir dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  provider: s3
  access_key_id: AKIAYB6YCLYJEJXDIRMQ
  secret_access_key:
    secure: CjeOPTl080CVSpmy089ei4dD8RMO7aSoPUlUbK7971afJX9k/AuLcJxsXaPpY0LE3nebxmeLXR85R2C7uGs2z/ZbzRrU+q9YgkVxkSUnuKSIsOVHex5bz3r+3Mci0/aHCMRk6ejEHjoOFYSxsXSEugbyixNdD8UtCU5gqQI5r8JbqcsByu6Ifd5m1cn/QcGEvamITvslOLPgILjNmxgfmDykJmuirwMZKkv+ptNknglXX455Kl9but/pW2+qBog6GGHZ/PdMgBzy8dZRokpGoJ0NdbkhmIRTs1iznbNiN2rpky9J4FUhzKe2GHEErdMJtq8z1UEyF+xbp7niENivSmvMKssOAfPrGTYa8cTDH7WLDWWa36YZRp/qGad0mOTrTop53tzHw/FcBdkXT6oEqluwGiesuvSbIY27esaSWL5xTDWN0o+mBsqMjg9aBHQj9AVoVXyt7SHguWP+wmzYlxuXZjwbeZvNM1DiGLDB1ruh2Ph11xAn7YEhEKoxnXgUQTwzQqst+z5MS6WoONg0nSIfUjb7F7vyqDZQKQrOyGC9Au7Zf57YI1wrzOFRE2veM1Pkkpzz3OFWndLkABrFyQSA+p787jULzsnQ/Y6dsz6eST+Cf+m64RD7xmrr+VzvDWgAU4oIq3CXpRN4xFxJzcFTMIJYQOnvX/ofjXlHTlg=
  bucket: ZJdOUO9sN3WZBV3K7IKYBV8ElJq9CffIhelabuw8
  local-dir: dpl_cd_upload
  acl: private
  on:
    repo: Lauviah0622/backend-deploy-test
    branch: main
  skip_cleanup: 'true'
